### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/chat-server#13]
From now we are going to serve each request using [WebSockets](https://ru.wikipedia.org/wiki/WebSocket) and [Tornado](http://www.tornadoweb.org/en/stable/).

Those are some steps for us in order to proceed with it:
- [x] Carefully remove old code :fire: 
- [x] Add a subclass of `WebSocketHandler`
- [x] Write the main logic of our revamped server :pencil2:
- [ ] Also add some tests :white_check_mark:

This is going to be a marvel :sparkles:
