### ISSUE TITLE
Add encryption process

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/chat-server#3]
### Description
We didn't have anything that would make hard to steal data from our chat. Our idea is to use RSA as encryption method.

### TODO
These are the steps that we're going to have on server:
- [x] Create a new set of public/private keys during starting up.
- [x] Send the public key on each request from client.
- [x] Decrypt each received packet and.....
- [x] Encrypt the answer that we are going to send.

### Special links
* https://github.com/sybrenstuvel/python-rsa
